/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedDemo: typeof import('./components/AdvancedDemo.vue')['default']
    DonutChart: typeof import('./components/DonutChart.vue')['default']
    DonutChartLegend: typeof import('./components/DonutChartLegend.vue')['default']
    EchartsComponent: typeof import('./components/EchartsComponent.vue')['default']
    InvestmentAssetSheet: typeof import('./components/InvestmentAssetSheet.vue')['default']
    InvestmentAssetSheet_old: typeof import('./components/InvestmentAssetSheet_old.vue')['default']
    ModernBottomSheet: typeof import('./components/ModernBottomSheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleBottomSheetForm: typeof import('./components/SimpleBottomSheetForm.vue')['default']
    SmartInvestmentAssetSheet: typeof import('./components/SmartInvestmentAssetSheet.vue')['default']
    StorageDemo: typeof import('./components/StorageDemo.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanTag: typeof import('vant/es')['Tag']
    VantDemo: typeof import('./components/VantDemo.vue')['default']
  }
}
